sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/sound\/pci\/hda/g" /home/redfeast/50G/rm2pk/sound/pci/hda/hda_intel_trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/sound\/pci\/hda/g" /home/redfeast/50G/rm2pk/sound/pci/hda/hda_controller_trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/sound\/core/g" /home/redfeast/50G/rm2pk/sound/core/pcm_trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/sound\/hda/g" /home/redfeast/50G/rm2pk/sound/hda/trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/kernel\/trace/g" /home/redfeast/50G/rm2pk/kernel/trace/trace_events_filter_test.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/kernel\/trace/g" /home/redfeast/50G/rm2pk/kernel/trace/trace_benchmark.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/samples\/trace_events/g" /home/redfeast/50G/rm2pk/samples/trace_events/trace-events-sample.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/ras/g" /home/redfeast/50G/rm2pk/drivers/ras/ras.c
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/mtd\/devices/g" /home/redfeast/50G/rm2pk/drivers/mtd/devices/docg3.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/staging\/android\/trace/g" /home/redfeast/50G/rm2pk/drivers/staging/android/trace/sync.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/staging\/android\/trace/g" /home/redfeast/50G/rm2pk/drivers/staging/android/trace/lowmemorykiller.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/staging\/rdma\/hfi1/g" /home/redfeast/50G/rm2pk/drivers/staging/rdma/hfi1/trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/misc\/mei/g" /home/redfeast/50G/rm2pk/drivers/misc/mei/mei-trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/misc\/cxl/g" /home/redfeast/50G/rm2pk/drivers/misc/cxl/trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/usb\/host/g" /home/redfeast/50G/rm2pk/drivers/usb/host/xhci-trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/usb\/dwc3/g" /home/redfeast/50G/rm2pk/drivers/usb/dwc3/trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/video\/adf/g" /home/redfeast/50G/rm2pk/drivers/video/adf/adf_trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/video\/fbdev\/msm/g" /home/redfeast/50G/rm2pk/drivers/video/fbdev/msm/mdss_mdp_trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/soc\/qcom/g" /home/redfeast/50G/rm2pk/drivers/soc/qcom/tracer_pkt_private.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/base\/regmap/g" /home/redfeast/50G/rm2pk/drivers/base/regmap/trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/gpu\/msm/g" /home/redfeast/50G/rm2pk/drivers/gpu/msm/kgsl_trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/gpu\/msm/g" /home/redfeast/50G/rm2pk/drivers/gpu/msm/adreno_trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/gpu\/drm\/amd\/scheduler/g" /home/redfeast/50G/rm2pk/drivers/gpu/drm/amd/scheduler/gpu_sched_trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/gpu\/drm\/amd\/amdgpu/g" /home/redfeast/50G/rm2pk/drivers/gpu/drm/amd/amdgpu/amdgpu_trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/gpu\/drm\/msm/g" /home/redfeast/50G/rm2pk/drivers/gpu/drm/msm/msm_trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/gpu\/drm\/msm\/sde/g" /home/redfeast/50G/rm2pk/drivers/gpu/drm/msm/sde/sde_trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/gpu\/drm\/i915/g" /home/redfeast/50G/rm2pk/drivers/gpu/drm/i915/i915_trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/gpu\/drm/g" /home/redfeast/50G/rm2pk/drivers/gpu/drm/drm_trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/gpu\/drm\/radeon/g" /home/redfeast/50G/rm2pk/drivers/gpu/drm/radeon/radeon_trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/net\/wireless\/ath\/ath6kl/g" /home/redfeast/50G/rm2pk/drivers/net/wireless/ath/ath6kl/trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/net\/wireless\/ath\/wil6210/g" /home/redfeast/50G/rm2pk/drivers/net/wireless/ath/wil6210/trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/net\/wireless\/ath/g" /home/redfeast/50G/rm2pk/drivers/net/wireless/ath/trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/net\/wireless\/ath\/ath5k/g" /home/redfeast/50G/rm2pk/drivers/net/wireless/ath/ath5k/trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/net\/wireless\/ath\/ath10k/g" /home/redfeast/50G/rm2pk/drivers/net/wireless/ath/ath10k/trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/net\/wireless\/mediatek\/mt7601u/g" /home/redfeast/50G/rm2pk/drivers/net/wireless/mediatek/mt7601u/trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/net\/wireless\/iwlwifi/g" /home/redfeast/50G/rm2pk/drivers/net/wireless/iwlwifi/iwl-devtrace-data.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/net\/wireless\/iwlwifi/g" /home/redfeast/50G/rm2pk/drivers/net/wireless/iwlwifi/iwl-devtrace-ucode.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/net\/wireless\/iwlwifi/g" /home/redfeast/50G/rm2pk/drivers/net/wireless/iwlwifi/iwl-devtrace-msg.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/net\/wireless\/iwlwifi/g" /home/redfeast/50G/rm2pk/drivers/net/wireless/iwlwifi/iwl-devtrace-iwlwifi.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/net\/wireless\/iwlwifi/g" /home/redfeast/50G/rm2pk/drivers/net/wireless/iwlwifi/iwl-devtrace-io.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/net\/wireless\/brcm80211\/brcmfmac/g" /home/redfeast/50G/rm2pk/drivers/net/wireless/brcm80211/brcmfmac/tracepoint.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/net\/wireless\/brcm80211\/brcmsmac/g" /home/redfeast/50G/rm2pk/drivers/net/wireless/brcm80211/brcmsmac/brcms_trace_brcmsmac_msg.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/net\/wireless\/brcm80211\/brcmsmac/g" /home/redfeast/50G/rm2pk/drivers/net/wireless/brcm80211/brcmsmac/brcms_trace_brcmsmac_tx.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/net\/wireless\/brcm80211\/brcmsmac/g" /home/redfeast/50G/rm2pk/drivers/net/wireless/brcm80211/brcmsmac/brcms_trace_brcmsmac.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/net\/ethernet\/msm/g" /home/redfeast/50G/rm2pk/drivers/net/ethernet/msm/rndis_ipa_trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/devfreq/g" /home/redfeast/50G/rm2pk/drivers/devfreq/devfreq_trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/media\/platform\/msm\/sde\/rotator/g" /home/redfeast/50G/rm2pk/drivers/media/platform/msm/sde/rotator/sde_rotator_trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/media\/platform\/coda/g" /home/redfeast/50G/rm2pk/drivers/media/platform/coda/trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/android/g" /home/redfeast/50G/rm2pk/drivers/android/binder_trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/platform\/msm\/ipa\/ipa_v2/g" /home/redfeast/50G/rm2pk/drivers/platform/msm/ipa/ipa_v2/ipa_trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/platform\/msm\/ipa\/ipa_v3/g" /home/redfeast/50G/rm2pk/drivers/platform/msm/ipa/ipa_v3/ipa_trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/drivers\/platform\/msm\/mhi/g" /home/redfeast/50G/rm2pk/drivers/platform/msm/mhi/mhi_trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/virt\/kvm\/arm/g" /home/redfeast/50G/rm2pk/virt/kvm/arm/trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/net\/mac80211/g" /home/redfeast/50G/rm2pk/net/mac80211/trace_msg.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/net\/mac80211/g" /home/redfeast/50G/rm2pk/net/mac80211/trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/net\/rmnet_data/g" /home/redfeast/50G/rm2pk/net/rmnet_data/rmnet_data_trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/net\/mac802154/g" /home/redfeast/50G/rm2pk/net/mac802154/trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/net\/wireless/g" /home/redfeast/50G/rm2pk/net/wireless/trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/net\/ieee802154/g" /home/redfeast/50G/rm2pk/net/ieee802154/trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/arch\/mips\/kvm/g" /home/redfeast/50G/rm2pk/arch/mips/kvm/trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/arch\/s390\/include\/asm\/trace/g" /home/redfeast/50G/rm2pk/arch/s390/include/asm/trace/diag.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/arch\/s390\/kvm/g" /home/redfeast/50G/rm2pk/arch/s390/kvm/trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/arch\/arm64\/kernel/g" /home/redfeast/50G/rm2pk/arch/arm64/kernel/trace-events-emulation.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/arch\/arm64\/kernel/g" /home/redfeast/50G/rm2pk/arch/arm64/kernel/perf_trace_user.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/arch\/arm64\/kernel/g" /home/redfeast/50G/rm2pk/arch/arm64/kernel/perf_trace_counters.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/arch\/arm64\/kvm/g" /home/redfeast/50G/rm2pk/arch/arm64/kvm/trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/arch\/x86\/include\/asm\/trace/g" /home/redfeast/50G/rm2pk/arch/x86/include/asm/trace/irq_vectors.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/arch\/x86\/include\/asm\/trace/g" /home/redfeast/50G/rm2pk/arch/x86/include/asm/trace/exceptions.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/arch\/x86\/include\/asm\/trace/g" /home/redfeast/50G/rm2pk/arch/x86/include/asm/trace/mpx.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/arch\/x86\/kvm/g" /home/redfeast/50G/rm2pk/arch/x86/kvm/mmutrace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/arch\/x86\/kvm/g" /home/redfeast/50G/rm2pk/arch/x86/kvm/trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/arch\/x86\/entry\/vsyscall/g" /home/redfeast/50G/rm2pk/arch/x86/entry/vsyscall/vsyscall_trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/arch\/powerpc\/include\/asm/g" /home/redfeast/50G/rm2pk/arch/powerpc/include/asm/trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/arch\/powerpc\/kvm/g" /home/redfeast/50G/rm2pk/arch/powerpc/kvm/trace_hv.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/arch\/powerpc\/kvm/g" /home/redfeast/50G/rm2pk/arch/powerpc/kvm/trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/arch\/powerpc\/kvm/g" /home/redfeast/50G/rm2pk/arch/powerpc/kvm/trace_booke.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/arch\/powerpc\/kvm/g" /home/redfeast/50G/rm2pk/arch/powerpc/kvm/trace_pr.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/arch\/powerpc\/platforms\/cell\/spufs/g" /home/redfeast/50G/rm2pk/arch/powerpc/platforms/cell/spufs/sputrace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/arch\/arm\/kvm/g" /home/redfeast/50G/rm2pk/arch/arm/kvm/trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/fs\/gfs2/g" /home/redfeast/50G/rm2pk/fs/gfs2/trace_gfs2.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/fs\/xfs/g" /home/redfeast/50G/rm2pk/fs/xfs/xfs_trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/fs\/nfs/g" /home/redfeast/50G/rm2pk/fs/nfs/nfstrace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/fs\/nfs/g" /home/redfeast/50G/rm2pk/fs/nfs/nfs4trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/fs\/nfsd/g" /home/redfeast/50G/rm2pk/fs/nfsd/trace.h
sed -i.bakkk "s/.*\#define *TRACE_INCLUDE_PATH.*/\#define TRACE_INCLUDE_PATH \.\.\/\.\.\/fs\/ocfs2/g" /home/redfeast/50G/rm2pk/fs/ocfs2/ocfs2_trace.h
